version: "3.9"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-container
    environment:
      SA_PASSWORD: "Senha@123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql

  api:
    build: .
    container_name: minhaapi-container
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=MinhaApiDb;User Id=sa;Password=Senha@123;TrustServerCertificate=True"

volumes:
  sqlserverdata:
